### ISSUE TITLE
Update requirements RedPandas

### ISSUE THREAD

**Issue by MeritxellC** [RedVoxInc/redpandas#1]
Latest version of numpy 1.22.0
obspy 1.3.0

**Comment by anthonyjchriste** [comment]
Please also look at updating other requirements. pyarrow is a few version behind and could be updated in lockstep with the SDK.

**Comment by MeritxellC** [comment]
I took out the requirements that overlap with the SDK so that redpandas directly uses the sdk's version when you install/upgrade the redvox sdk.

**Comment by MeritxellC** [comment]
Updated setup.py to match the sdk's 3.8.
Cleaned up requirements, fundamental overlapped libraries (the holy grail: scipy, pandas, numpy)with sdk now have no version.
